# Generated by Django 4.2.11 on 2024-10-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Vegetarian', 'Vegetarian')], max_length=20)),
                ('special_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
